export enum WalletErrorCodes {
  GENERIC_ERROR = 'GENERIC_ERROR',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  WALLET_LOCKED = 'WALLET_LOCKED',
  WALLET_NOT_FOUND = 'WALLET_NOT_FOUND',
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',
}
